version: "3.9"

services:
  sentraguard-api:
    build: .
    container_name: sentraguard-api
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  sentraguard-ui:
    build: .
    container_name: sentraguard-ui
    ports:
      - "8501:8501"
    command: streamlit run ui/streamlit_app.py --server.address 0.0.0.0
    depends_on:
      - sentraguard-api